// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARG0iXHzznDNqbCco8mQ6Rmrad7We-Ngg',
    appId: '1:647217947563:web:27ec6e5b0438874ca5a8ee',
    messagingSenderId: '647217947563',
    projectId: 'daftarbelanja-2d4c7',
    authDomain: 'daftarbelanja-2d4c7.firebaseapp.com',
    databaseURL: 'https://daftarbelanja-2d4c7-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-2d4c7.firebasestorage.app',
    measurementId: 'G-LRF493JSFD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl-Btf9toYGqXNiZqEdchMqHaAJb9tCn4',
    appId: '1:647217947563:android:448a53bc20deac84a5a8ee',
    messagingSenderId: '647217947563',
    projectId: 'daftarbelanja-2d4c7',
    databaseURL: 'https://daftarbelanja-2d4c7-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-2d4c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpGGwShl5DT6pWvM98gZCJMLeJEfUZYUQ',
    appId: '1:647217947563:ios:b3ef82620f3dc918a5a8ee',
    messagingSenderId: '647217947563',
    projectId: 'daftarbelanja-2d4c7',
    databaseURL: 'https://daftarbelanja-2d4c7-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-2d4c7.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpGGwShl5DT6pWvM98gZCJMLeJEfUZYUQ',
    appId: '1:647217947563:ios:b3ef82620f3dc918a5a8ee',
    messagingSenderId: '647217947563',
    projectId: 'daftarbelanja-2d4c7',
    databaseURL: 'https://daftarbelanja-2d4c7-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-2d4c7.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARG0iXHzznDNqbCco8mQ6Rmrad7We-Ngg',
    appId: '1:647217947563:web:0640a94f2c65f769a5a8ee',
    messagingSenderId: '647217947563',
    projectId: 'daftarbelanja-2d4c7',
    authDomain: 'daftarbelanja-2d4c7.firebaseapp.com',
    databaseURL: 'https://daftarbelanja-2d4c7-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-2d4c7.firebasestorage.app',
    measurementId: 'G-NJ3496WM1Y',
  );
}
